server:
  port: 7777
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ 
spring:
  application:
    name: usk-gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: order
        uri: lb://order-service
        predicates:
        - Path=/order/**