version: '3.8'

services:
        USK-GATEWAY:
                image: gateway
                links:
                        - "ORDER-SERVICE"
                        - "USER-SERVICE"
                        - "EUREKA-SERVER"
                ports:
                        - "2020:2020"
        EUREKA-SERVER:
                image: eureka
                links:
                        - "ORDER-SERVICE"
                        - "USER-SERVICE"
                        - "USK-GATEWAY"
                ports:
                        - "8761:8761"
        USER-SERVICE:
                image: user
                links:
                        - "ORDER-SERVICE"
        ORDER-SERVICE:
                image: order

