version: '3.8'

services:
        USK-GATEWAY:
                image: usksanthu/gateway3
                links:
                        - "ORDER-SERVICE"
                        - "USER-SERVICE"
                        - "EUREKA-SERVER"
                ports:
                        - "2020:2020"
        EUREKA-SERVER:
                image: usksanthu/eureka3
                links:
                        - "ORDER-SERVICE"
                        - "USER-SERVICE"
                        - "USK-GATEWAY"
                ports:
                        - "8761:8761"
        USER-SERVICE:
                image: usksanthu/user3
                links:
                        - "ORDER-SERVICE"
        ORDER-SERVICE:
                image: usksanthu/order3

