server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true    
     
spring:
  application:
    name: usk-gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/user/**
    loadbalancer:
      enabled: false