server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
     
spring:
  application:
    name: usk-gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: http://localhost:8081
        predicates:
        - Path=/user/**