version: '3.8'

services:
        USK-GATEWAY:
                image: gateway
                container_name: gateway
                ports:
                        - "8888:8888"
        EUREKA-SERVER:
                image: eureka
                container_name: eureka-server
                ports:
                        - "8761:8761"
        USER-SERVICE:
                image: user
                container_name: user-service
                ports:
                        - "8081:8081"
