version: '3.8'

services:
        JWT-SERVICE:
                image: sb-jwt
                links:
                        - "mysql-server"
                ports:
                        - "8083:8083"
        mysql-server:
                image: mysql
                environment:
                        - MYSQL_DATABASE=jwt_test
                        - MYSQL_ROOT_PASSWORD=root

