version: '3.8'

services:
        USK-GATEWAY:
                image: usksanthu/gateway3
                ports:
                        - "2020:2020"
        EUREKA-SERVER:
                image: usksanthu/eureka2
                ports:
                        - "8761:8761"
        USER-SERVICE:
                image: usksanthu/user2
                ports:
                        - "8081:8081"
        ORDER-SERVICE:
                image: usksanthu/order2

